### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by zmeers** [themefisher/Academia-hugo#11]
Hi!

Thank you for the theme; it's beautiful.

I'm trying to upload a new favicon to override the "A" favicon that comes with the theme. I've replaced the files in static/img and recompiled my site, but nothing is showing up. Do I need to specify something in one of the .toml files?

Thanks,
Zoe

**Comment by Somrat37** [comment]
Maybe this is happening for your browser cache. try to clear your browser cache.

**Comment by zmeers** [comment]
Thanks, that solved it.
