### ISSUE TITLE
CSS: failed to transform "main_parsed.scss"

### ISSUE THREAD

**Issue by johndoe31415** [themefisher/academia-hugo#13]
Hi there,

I'm using the latest Hugo build on Linux x86_64 (Hugo Static Site Generator v0.73.0-428907CC linux/amd64 BuildDate: 2020-06-23T16:30:43Z). When I create a site using academia-hugo, some of the generated files work if the translated version is copied from the exampleSite, but I cannot recreate those sites myself. To reproduce:

```
$ hugo new site new
$ cd new/themes
$ git clone https://github.com/themefisher/academia-hugo.git
$ cd ../..
$ cp -r themes/academia-hugo/exampleSite/. .
$ echo 'theme = "academia-hugo"' >>config.toml 
$ hugo server
```

This works nicely and I see the default site. However, when I Ctrl-C out of that server and try a clean build:

```
$ rm -fr ./resources/_gen
$ hugo serve
Built in 3090 ms
Error: Error building site: TOCSS: failed to transform "main_parsed.scss" (text/x-scss): resource "scss/sass/main.scss_af4713394d203c6760d5068301ff2656" not found in file cache
```

I cannot get Hugo to tell me exactly why it cannot translate `main_parsed.scss`; strace clearly shows it opens the file, but I have no clue why rendering the template fails.

Best,
Joe

**Comment by developer-evan** [comment]
please use hugo extended version, thanks
