### ISSUE TITLE
Hugo Server works but Hugo (build) has no css or js

### ISSUE THREAD

**Issue by rebelwarrior** [themefisher/academia-hugo#14]
When I use hugo server the site looks fine when I use hugo to build the site on public, the css and js don't load and the site looks like a skeleton. 
Tried using a baseUrl of "/" as recommended. Same result.

**Comment by developer-evan** [comment]
hey there, it doesn't work like that. When you generate `hugo` you need to specify the baseURL that you want to publish. then after generate the public folder, you need to upload the file there. then it will work.

**Comment by rebelwarrior** [comment]
Figured out what was going on. 

This blog explains it: 

https://alison.rbind.io/post/2019-03-04-hugo-troubleshooting/

**Comment by rebelwarrior** [comment]
Basically what happens is that if the baseURL is set to "/" then the css, js and image (img) files look for files with a double "//" in them. This fails and the site looks undressed. To solve this I re-wrote the calls for css, js and img files on the outputted `index.html` file in site. This fixes the problem. 

When you go to output for deployment rather than testing locally set the baseUrl correctly to the website's site.
