### ISSUE TITLE
Icons in Text

### ISSUE THREAD

**Issue by d-bohn** [themefisher/academia-hugo#15]
Hello,

Is there a way to add icons (FontAwesome or otherwise) directly to "plain text" (i.e. not the header) using a shortcode? I tried using hugo-academic's "icon" shortcode, but that did not seem to work. I also tried adding my own shortcode to the theme and base (`./layouts/shortcodes`) folder for icons and I can't seem to get it to work.

**Comment by tfsomrat** [comment]
Hello @d-bohn 

This feature is not available in this theme. If you need it, we can build it for you. contact us at mehedi@themefisher.com for any kind of customization (paid)
