### ISSUE TITLE
Not able to change the font size

### ISSUE THREAD

**Issue by matsbror** [themefisher/academia-hugo#17]
I do not know what values to give to `font_size` in params.toml to make effect. I have tried with `s`, `small` without any change. 

I also searched the template and did not find a place where `font_size` was parsed. 

Great looking template though, so thanks!

Mermaid diagrams are not enabled the way as specified in the documentation, instead the `diagram` shortcode should be used.

**Comment by sojonatgithub** [comment]
Hey @matsbror,
To change font-size you have to edit files from the directory `/data/fonts/`

Thank you for your query
