### ISSUE TITLE
page-links-div partial does not build DOI links if no other links present

### ISSUE THREAD

**Issue by pintodossantos** [themefisher/academia-hugo#18]
In `page-links-div.html` in line:

https://github.com/themefisher/academia-hugo/blob/f4d5eba11eb87ca180bde088483d2a8c339e5431/layouts/partials/page_links_div.html#L18

DOI is not specified, so if DOI is only link, button  is not built. Could be fixed easily by changing this line to:

`{{ if $cite_link | or $pdf_link | or .Params.external_link | or .Params.url_preprint | or .Params.url_pdf | or .Params.url_slides | or .Params.url_video | or .Params.url_source | or .Params.url_code | or .Params.url_dataset | or .Params.doi | or .Params.url_poster | or .Params.url_project | or .Params.links | or .Params.projects | or .Params.slides }}`

**Comment by somratpro** [comment]
Hello @pintodossantos ,

Thanks for your concern. It will be great if you make a pull request with this fix, or we will fix it on our next update.

**Comment by pintodossantos** [comment]
Thanks for your reply @somratpro! Pull request created. :)

**Comment by somratpro** [comment]
I have merged your PR, thanks for being with Themefisher.
