### ISSUE TITLE
Support for Microsoft Clarity

### ISSUE THREAD

**Issue by matsbror** [themefisher/academia-hugo#19]
I made a branch with support  for Microsoft Clarity. I added the configuration in the `params.toml` which is where I think also the google analytics configuration should be made. You have not specified how you want contributions so I just made a diff which I include here.
[clarity.zip](https://github.com/themefisher/academia-hugo/files/5671448/clarity.zip)

**Comment by matsbror** [comment]
Actually, I managed to make a pull request.

**Comment by somratpro** [comment]
Hello @matsbror 

Thanks for your contribution, I have merged your PR, hope you will stay connected with us.
