### ISSUE TITLE
Not compatible with Hugo Academic Latest release (v4.5)

### ISSUE THREAD

**Issue by the-redback** [themefisher/academia-hugo#2]
Thanks for the nice design and stuff.

While using my current website configuration with Academia (which works fine with Academic v4.5), I am getting some error. Looks like Academia is not compatible with Academic-v4.5 release?

Thanks

**Comment by dominikclemente** [comment]
I'm getting this error when I execute view.sh `Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:7:3: executing "main" at <partial "widget_page.html" .>: error calling partial: "/home/autodidactic/lib/abradatas/hugo-abradabra/themes/hugo-academic/layouts/partials/widget_page.html:75:60": execute of template failed: template: partials/widget_page.html:71:9: executing "partials/widget_page.html" at <partial $widget_path $widget_args>: error calling partial: "/home/autodidactic/lib/abradatas/hugo-abradabra/themes/hugo-academic/layouts/partials/widgets/contact.html:75:60": execute of template failed: template: partials/widgets/contact.html:75:60: executing "partials/widgets/contact.html" at <markdownify>: error calling markdownify: unable to cast maps.Params{"city":"Stanford", "country":"United States", "country_code":"US", "postcode":"94305", "region":"CA", "street":"450 Serra Mall"} of type maps.Params to string`

**Comment by daniel-wing** [comment]
I am just learning, so I spend 2 days trying to figure it out, googling the error, treating to understand what I was doing wrong, all before coming to post an issue. And here I am, facing exactly the same. Lesson learned, next time I will come and check what the known issues are.

**Comment by niklas-fischer** [comment]
I tried the same installation method and ended up facing the same error. Is there any way to get it running?

**Comment by developer-evan** [comment]
This theme is forked from the Academic theme. But it does not support the academic latest release anymore. Now it has it's won way to set up and run this theme.

**Comment by the-redback** [comment]
I am closing this issue as it has different installation procedure now.

**Comment by jainkhyati** [comment]
Can someone please help with the installation procedure now? Which version of academic theme would be needed?
