### ISSUE TITLE
Email subscription section

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [themefisher/academia-hugo#22]
The theme supposedly has an email subscription section 

![image](https://user-images.githubusercontent.com/9049533/103017851-7fd9b980-4544-11eb-8fa4-d60d80fb5af8.jpeg)

but I can't find it.

Any help will be much appreciated.

**Comment by tfsomrat** [comment]
Hello @rodrigoalcarazdelaosa 

I am sorry this feature is not available, If you want it, we can create it for you, contact us at mehedi@themefisher.com (paid)
