### ISSUE TITLE
Bug on list layout in featured widget

### ISSUE THREAD

**Issue by JPUnD** [themefisher/academia-hugo#26]
After trying out the featured widget with the list design all of my publications/projects/posts looked like:
![image](https://user-images.githubusercontent.com/41581666/108129516-3621d100-70a6-11eb-95cc-56cc966d975a.png)

Comparing it to the original academic template:
![image](https://user-images.githubusercontent.com/41581666/108129536-40dc6600-70a6-11eb-9bd6-11d984abed4f.png)

Is this intended behavior? It doesn't look like considering how close together the titles are, I feel like each should be in a new line. The design also doesn't improve when viewing it in cellphone mode.

In comparison with the citation design:
![image](https://user-images.githubusercontent.com/41581666/108129975-c5c77f80-70a6-11eb-97de-2938b70048c1.png)

Which should be expected to happen in the list design aswell.

**Comment by somratpro** [comment]
Hello @JPUnD 

Thanks for your concern, We fixed that issue, you can download the latest code now.

**Comment by JPUnD** [comment]
Thanks, it does fix the overlap.

However I would just like to point that the publications are now centered instead of aligned to the left:
![image](https://user-images.githubusercontent.com/41581666/108609014-d89dc500-73c2-11eb-8cf1-76a2bd1b2a2f.png)

I'm not sure if this is intended behavior or not, but considering it's a change I decided to report it back anyways.

**Comment by JPUnD** [comment]
If somebody ever finds this thread on the future and wishes to have things more to the left simply adjusting the number of the value in `li_list.html`:
<div class="view-list-item col-lg-8 mx-auto" itemscope itemtype="http://schema.org/{{$microdata_type}}">

Will do it. Because I wanted different spacing in the featured and in the publications category, I created a file `li_list_featured.html` and in the widget partial `featured.html` instead of using `li_list` I used `li_list_featured` which contained the desired modifications.
