### ISSUE TITLE
Misaligned footer

### ISSUE THREAD

**Issue by JPUnD** [themefisher/academia-hugo#27]
Hi there, so this might seem like a little thing, and it is, but I noticed it and now I'm unable to un-notice it.

Here's a print screen from the live preview of the theme with a line I made:
![image](https://user-images.githubusercontent.com/41581666/108913573-0fbde180-7622-11eb-89c3-83eaabb1bc8d.png)

As you can see, and the same thing happens in my website, it's not perfectly centered.

Thanks in advance!

**Comment by somratpro** [comment]
Hey @JPUnD 

Thanks for your concern, we fixed that issue. please download the latest code.
